config {
  type: "table",
  schema: "sc_gold",
  name: "t_dim_company",
  description: "Dimension table for taxi companies"
}

SELECT
  CASE WHEN company IS NULL OR TRIM(company) = '' THEN -1
    ELSE ROW_NUMBER() OVER (ORDER BY company)
  END AS company_id,
  COALESCE(company, '') AS company,
  CURRENT_TIMESTAMP() AS _gold_load_dttm_utc
FROM (SELECT DISTINCT company FROM ${ref("sc_silver", "t_taxi_trips")})
ORDER BY company_id